using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Swashbuckle.AspNetCore.Filters;
using Scalar.AspNetCore;

namespace InterceptorDemoApp.Api.Extensions
{
    public static class ScalarWithSwaggerExtensions
    {
        public static IServiceCollection AddScalarWithSawgger(this IServiceCollection services)
        {
            services.AddOpenApi();
            services.AddSwaggerGen(c =>
            {
                // Enables automatic example filters for Swashbuckle
                c.ExampleFilters();
            });

            // Registers example classes from your assembly
            services.AddSwaggerExamplesFromAssemblyOf<global::Program>();

            return services;
        }

        public static WebApplication UseSwaggerForDevelopment(this WebApplication app)
        {
            if (app.Environment.IsDevelopment())
            {
                // Exposes the JSON document at /swagger/v1/swagger.json
                app.UseSwagger();

                app.MapOpenApi();

                // Map Scalar Interface
                app.MapScalarApiReference(options =>
                {
                    // We point the Scalar UI to the document generated by Swashbuckle because
                    // Swashbuckle (Swagger) inspects the type of each call and auto-generates a default example value.
                    // In other words, it has a more complete document than the OpenAPI output
                    options.WithOpenApiRoutePattern("/swagger/v1/swagger.json");
                });
            }

            return app;
        }
    }
}
